from django.db import models
from datetime import datetime, timedelta
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.
class TripCategory(models.Model):
    description = models.CharField(max_length=20)

    def __str__(self) :
        return (self.description)

class Destination(models.Model) :
    tripcategory = models.OneToOneField(TripCategory, models.CASCADE)
    title = models.CharField(max_length=50)
    days = models.IntegerField(default=0)
    cost = models.DecimalField(max_digits=10, decimal_places=2) 
    photo_main= models.ImageField(upload_to='photos')  
    is_active = models.BooleanField(default=True)
    leave_date = models.DateField(default=datetime.today, blank=True)

    def __str__ (self):
                    return (self.title)
                
    @property
    def return_date(self) :
        return (self.leave_date + timedelta(days=self.days))

class Customer(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    user_name = models.CharField(max_length=20)
    password = models.CharField(max_length=20)
    email = models.EmailField(max_length=100)    
    phone = models.CharField(max_length=13, blank=True)
    destinations = models.ManyToManyField(Destination, blank=True)

    def __str__(self):
        return (self.full_name)

    @property # this is not part of the table
    def full_name(self):
        return '%s %s' % (self.first_name, self.last_name)

    def save(self):
        self.first_name = self.first_name.upper()
        super(Customer, self).save() # Call the "real" save() method.    

class Contact_Information(models.Model):
    contact_phone = models.CharField(max_length=10)

    def __str__(self):
        phone = '(%s) %s-%s' %(self.contact_phone[0:3],self.contact_phone[3:6],self.contact_phone[6:10])
        return phone  
        

class Employee(models.Model):
    TITLE = (
        ('Ms.', 'MISS'),
        ('Mr.', 'MR.'),
        ('Mrs.', 'MRS.'),
        ('Mx', 'MX'),
    )

    emp_first = models.CharField(max_length=20)
    emp_last = models.CharField(max_length=20)
    emp_title = models.CharField(max_length=4, choices=TITLE, null=True, blank=True)
    emp_state = models.ForeignKey('State', null=True, blank=True, on_delete=models.SET_NULL)
    contact_information = models.OneToOneField(Contact_Information, on_delete=models.CASCADE)
    # emp_skills = models.ManyToManyField('Skill')

    def __str__(self):
        return (self.emp_first + " " + self.emp_last)   

class State(models.Model) :
    state_abbrev = models.CharField(max_length=2)
    state_description = models.CharField(max_length=30)

    def __str__(self):
        return (self.state_description)    

class Listing_Status(models.Model) :
    ListingStatus_ID = models.AutoField(primary_key=True)
    Status = models.CharField(max_length=20)
    StatusDescription = models.CharField(max_length=200)

    def __str__(self):
        return (self.Status)
        
class Applicant(models.Model) :
    Applicant_ID = models.AutoField(primary_key=True)
    AFirstName = models.CharField(max_length=50)
    ALastName = models.CharField(max_length=50)
    AEmail = models.CharField(max_length=50)
    AUsername = models.CharField(max_length=50)

    def __str__(self):
        return (self.AFirstName + " " + self.ALastName)
        
    def save(self):
        self.AFirstName = self.AFirstName
        super(Applicant, self).save() # Call the "real" save() method.   

class Company(models.Model) :
    Organization_ID = models.AutoField(primary_key=True)
    CompName = models.CharField(max_length=50)
    CompEmail = models.CharField(max_length=50)
    CompAddress = models.CharField(max_length=50)

    def __str__(self):
        return (self.CompName)

class Skills(models.Model) :
    Skills_ID = models.AutoField(primary_key=True)
    matching_skills = models.IntegerField(default=0, blank=True, null=True)
    skill_a_b_testing = models.IntegerField(default=0)
    skill_adobe_illustrator = models.IntegerField(default=0)
    skill_adobe_photoshop = models.IntegerField(default=0)
    skill_ai = models.IntegerField(default=0)
    skill_ajax = models.IntegerField(default=0)
    skill_analytical = models.IntegerField(default=0)
    skill_analytics = models.IntegerField(default=0)
    skill_android = models.IntegerField(default=0)
    skill_angular = models.IntegerField(default=0)
    skill_angularjs = models.IntegerField(default=0)
    skill_apache = models.IntegerField(default=0)
    skill_apex = models.IntegerField(default=0)
    skill_api_rest = models.IntegerField(default=0)
    skill_apis = models.IntegerField(default=0)
    skill_arduino = models.IntegerField(default=0)
    skill_artificial_neural_network = models.IntegerField(default=0)
    skill_asp_net = models.IntegerField(default=0)
    skill_asp_net_core = models.IntegerField(default=0)
    skill_asp_net_mvc = models.IntegerField(default=0)
    skill_assembleur = models.IntegerField(default=0)
    skill_assembly = models.IntegerField(default=0)
    skill_attention_to_detail = models.IntegerField(default=0)
    skill_autocad = models.IntegerField(default=0)
    skill_autonome = models.IntegerField(default=0)
    skill_awk = models.IntegerField(default=0)
    skill_aws = models.IntegerField(default=0)
    skill_backend = models.IntegerField(default=0)
    skill_bash = models.IntegerField(default=0)
    skill_big_data = models.IntegerField(default=0)
    skill_bootstrap = models.IntegerField(default=0)
    skill_c_plus_plus = models.IntegerField(default=0)
    skill_cassandra = models.IntegerField(default=0)
    skill_centreon = models.IntegerField(default=0)
    skill_certifications = models.IntegerField(default=0)
    skill_cgi = models.IntegerField(default=0)
    skill_cics = models.IntegerField(default=0)
    skill_cisco = models.IntegerField(default=0)
    skill_cloud_computing = models.IntegerField(default=0)
    skill_coaching = models.IntegerField(default=0)
    skill_cobol = models.IntegerField(default=0)
    skill_codeigniter = models.IntegerField(default=0)
    skill_coding = models.IntegerField(default=0)
    skill_cognos = models.IntegerField(default=0)
    skill_collaboration = models.IntegerField(default=0)
    skill_communication = models.IntegerField(default=0)
    skill_communication_technologies = models.IntegerField(default=0)
    skill_consulting = models.IntegerField(default=0)
    skill_content_marketing = models.IntegerField(default=0)
    skill_continuous_integration = models.IntegerField(default=0)
    skill_control_systems = models.IntegerField(default=0)
    skill_cordova = models.IntegerField(default=0)
    skill_creating_data = models.IntegerField(default=0)
    skill_critical_thinking = models.IntegerField(default=0)
    skill_css = models.IntegerField(default=0)
    skill_cucumber = models.IntegerField(default=0)
    skill_customer_service = models.IntegerField(default=0)
    skill_cvs = models.IntegerField(default=0)
    skill_data_analysis = models.IntegerField(default=0)
    skill_data_analytics = models.IntegerField(default=0)
    skill_data_collection = models.IntegerField(default=0)
    skill_data_engineers = models.IntegerField(default=0)
    skill_data_management = models.IntegerField(default=0)
    skill_data_mining = models.IntegerField(default=0)
    skill_data_processing = models.IntegerField(default=0)
    skill_data_quality = models.IntegerField(default=0)
    skill_data_visualisation = models.IntegerField(default=0)
    skill_data_visualization = models.IntegerField(default=0)
    skill_data_warehouse = models.IntegerField(default=0)
    skill_database_developers = models.IntegerField(default=0)
    skill_databases = models.IntegerField(default=0)
    skill_dax = models.IntegerField(default=0)
    skill_db = models.IntegerField(default=0)
    skill_debugging = models.IntegerField(default=0)
    skill_deep_learning = models.IntegerField(default=0)
    skill_design = models.IntegerField(default=0)
    skill_design_patterns = models.IntegerField(default=0)
    skill_designer = models.IntegerField(default=0)
    skill_desk = models.IntegerField(default=0)
    skill_devops = models.IntegerField(default=0)
    skill_diagnostics = models.IntegerField(default=0)
    skill_digital_marketing = models.IntegerField(default=0)
    skill_django = models.IntegerField(default=0)
    skill_documentation = models.IntegerField(default=0)
    skill_dom = models.IntegerField(default=0)
    skill_dos = models.IntegerField(default=0)
    skill_drupal = models.IntegerField(default=0)
    skill_dynamodb = models.IntegerField(default=0)
    skill_e_commerce = models.IntegerField(default=0)
    skill_eclipse = models.IntegerField(default=0)
    skill_electronics = models.IntegerField(default=0)
    skill_engineering = models.IntegerField(default=0)
    skill_ensemble = models.IntegerField(default=0)
    skill_entity_framework = models.IntegerField(default=0)
    skill_etl = models.IntegerField(default=0)
    skill_extjs = models.IntegerField(default=0)
    skill_fortran = models.IntegerField(default=0)
    skill_foundation = models.IntegerField(default=0)
    skill_framework = models.IntegerField(default=0)
    skill_frontend = models.IntegerField(default=0)
    skill_full_stack = models.IntegerField(default=0)
    skill_g_xc_xanie_logiciel = models.IntegerField(default=0)
    skill_git = models.IntegerField(default=0)
    skill_go = models.IntegerField(default=0)
    skill_google_maps = models.IntegerField(default=0)
    skill_graphic_design = models.IntegerField(default=0)
    skill_grav = models.IntegerField(default=0)
    skill_groovy = models.IntegerField(default=0)
    skill_grunt = models.IntegerField(default=0)
    skill_gsm = models.IntegerField(default=0)
    skill_gulp = models.IntegerField(default=0)
    skill_gwt = models.IntegerField(default=0)
    skill_hadoop = models.IntegerField(default=0)
    skill_hardware = models.IntegerField(default=0)
    skill_hbase = models.IntegerField(default=0)
    skill_hibernate = models.IntegerField(default=0)
    skill_hive = models.IntegerField(default=0)
    skill_html = models.IntegerField(default=0)
    skill_http = models.IntegerField(default=0)
    skill_ia = models.IntegerField(default=0)
    skill_implementation = models.IntegerField(default=0)
    skill_information_security = models.IntegerField(default=0)
    skill_innovation = models.IntegerField(default=0)
    skill_insights = models.IntegerField(default=0)
    skill_internet = models.IntegerField(default=0)
    skill_interpersonal = models.IntegerField(default=0)
    skill_ios = models.IntegerField(default=0)
    skill_iot = models.IntegerField(default=0)
    skill_iphone = models.IntegerField(default=0)
    skill_iptables = models.IntegerField(default=0)
    skill_itil = models.IntegerField(default=0)
    skill_javascript = models.IntegerField(default=0)
    skill_jcl = models.IntegerField(default=0)
    skill_jenkins = models.IntegerField(default=0)
    skill_joomla = models.IntegerField(default=0)
    skill_jquery = models.IntegerField(default=0)
    skill_jsf = models.IntegerField(default=0)
    skill_json = models.IntegerField(default=0)
    skill_jsp = models.IntegerField(default=0)
    skill_junit = models.IntegerField(default=0)
    skill_laravel = models.IntegerField(default=0)
    skill_leadership = models.IntegerField(default=0)
    skill_less = models.IntegerField(default=0)
    skill_linux = models.IntegerField(default=0)
    skill_listening = models.IntegerField(default=0)
    skill_lte = models.IntegerField(default=0)
    skill_lua = models.IntegerField(default=0)
    skill_mac = models.IntegerField(default=0)
    skill_machine_learning = models.IntegerField(default=0)
    skill_mariadb = models.IntegerField(default=0)
    skill_math_xc_xamatiques = models.IntegerField(default=0)
    skill_mathematics = models.IntegerField(default=0)
    skill_matlab = models.IntegerField(default=0)
    skill_maven = models.IntegerField(default=0)
    skill_mentoring = models.IntegerField(default=0)
    skill_microsoft = models.IntegerField(default=0)
    skill_microsoft_access = models.IntegerField(default=0)
    skill_microsoft_azure = models.IntegerField(default=0)
    skill_microsoft_excel = models.IntegerField(default=0)
    skill_microsoft_office = models.IntegerField(default=0)
    skill_microsoft_power_bi = models.IntegerField(default=0)
    skill_microsoft_project = models.IntegerField(default=0)
    skill_microsoft_visual = models.IntegerField(default=0)
    skill_microsoft_windows = models.IntegerField(default=0)
    skill_microstrategy = models.IntegerField(default=0)
    skill_mobile = models.IntegerField(default=0)
    skill_mockito = models.IntegerField(default=0)
    skill_modeling = models.IntegerField(default=0)
    skill_mongodb = models.IntegerField(default=0)
    skill_ms_access = models.IntegerField(default=0)
    skill_ms_excel = models.IntegerField(default=0)
    skill_ms_sql_server = models.IntegerField(default=0)
    skill_ms_visio = models.IntegerField(default=0)
    skill_ms_word = models.IntegerField(default=0)
    skill_multitasking = models.IntegerField(default=0)
    skill_mvvm = models.IntegerField(default=0)
    skill_mysql = models.IntegerField(default=0)
    skill_nagios = models.IntegerField(default=0)
    skill_network_security = models.IntegerField(default=0)
    skill_networks = models.IntegerField(default=0)
    skill_neural_networks = models.IntegerField(default=0)
    skill_nhibernate = models.IntegerField(default=0)
    skill_nlp = models.IntegerField(default=0)
    skill_node_js = models.IntegerField(default=0)
    skill_nodejs = models.IntegerField(default=0)
    skill_nosql = models.IntegerField(default=0)
    skill_obiee = models.IntegerField(default=0)
    skill_objective_c = models.IntegerField(default=0)
    skill_operating_system = models.IntegerField(default=0)
    skill_optimisations = models.IntegerField(default=0)
    skill_oracle = models.IntegerField(default=0)
    skill_organizational = models.IntegerField(default=0)
    skill_pascal = models.IntegerField(default=0)
    skill_pca = models.IntegerField(default=0)
    skill_penetration_testing = models.IntegerField(default=0)
    skill_pentaho = models.IntegerField(default=0)
    skill_perl = models.IntegerField(default=0)
    skill_phonegap = models.IntegerField(default=0)
    skill_php = models.IntegerField(default=0)
    skill_pl_sql = models.IntegerField(default=0)
    skill_postfix = models.IntegerField(default=0)
    skill_postgresql = models.IntegerField(default=0)
    skill_powerpoint = models.IntegerField(default=0)
    skill_powershell = models.IntegerField(default=0)
    skill_presentation = models.IntegerField(default=0)
    skill_prestashop = models.IntegerField(default=0)
    skill_priorities = models.IntegerField(default=0)
    skill_problem_solving = models.IntegerField(default=0)
    skill_processing = models.IntegerField(default=0)
    skill_programming = models.IntegerField(default=0)
    skill_project_management = models.IntegerField(default=0)
    skill_project_manager = models.IntegerField(default=0)
    skill_prototyping = models.IntegerField(default=0)
    skill_pspice = models.IntegerField(default=0)
    skill_python = models.IntegerField(default=0)
    skill_qc = models.IntegerField(default=0)
    skill_qlikview = models.IntegerField(default=0)
    skill_r_xc_xaseau = models.IntegerField(default=0)
    skill_redis = models.IntegerField(default=0)
    skill_renewable_energy = models.IntegerField(default=0)
    skill_reporting = models.IntegerField(default=0)
    skill_reporting_tools = models.IntegerField(default=0)
    skill_ruby = models.IntegerField(default=0)
    skill_s_xc_xacurit_xc_xa_informatique = models.IntegerField(default=0)
    skill_sap = models.IntegerField(default=0)
    skill_sas = models.IntegerField(default=0)
    skill_sass = models.IntegerField(default=0)
    skill_scala = models.IntegerField(default=0)
    skill_scrum = models.IntegerField(default=0)
    skill_sdk_android = models.IntegerField(default=0)
    skill_selenium = models.IntegerField(default=0)
    skill_sencha_touch = models.IntegerField(default=0)
    skill_sharepoint = models.IntegerField(default=0)
    skill_shell_unix = models.IntegerField(default=0)
    skill_shiny = models.IntegerField(default=0)
    skill_sip = models.IntegerField(default=0)
    skill_six_sigma = models.IntegerField(default=0)
    skill_sketchup = models.IntegerField(default=0)
    skill_soa = models.IntegerField(default=0)
    skill_soap = models.IntegerField(default=0)
    skill_social_media_marketing = models.IntegerField(default=0)
    skill_software_development = models.IntegerField(default=0)
    skill_software_knowledge = models.IntegerField(default=0)
    skill_solution_development = models.IntegerField(default=0)
    skill_spark = models.IntegerField(default=0)
    skill_spring = models.IntegerField(default=0)
    skill_spring_mvc = models.IntegerField(default=0)
    skill_sql = models.IntegerField(default=0)
    skill_sql_server = models.IntegerField(default=0)
    skill_sqlite = models.IntegerField(default=0)
    skill_statistical_analysis = models.IntegerField(default=0)
    skill_strategic_thinking = models.IntegerField(default=0)
    skill_svg = models.IntegerField(default=0)
    skill_svn = models.IntegerField(default=0)
    skill_swift = models.IntegerField(default=0)
    skill_swing = models.IntegerField(default=0)
    skill_symfony = models.IntegerField(default=0)
    skill_t_sql = models.IntegerField(default=0)
    skill_tableau = models.IntegerField(default=0)
    skill_teamwork = models.IntegerField(default=0)
    skill_tech_support = models.IntegerField(default=0)
    skill_technical = models.IntegerField(default=0)
    skill_telecom = models.IntegerField(default=0)
    skill_teradata = models.IntegerField(default=0)
    skill_time_management = models.IntegerField(default=0)
    skill_training = models.IntegerField(default=0)
    skill_troubleshooting = models.IntegerField(default=0)
    skill_typescript = models.IntegerField(default=0)
    skill_ui_ux = models.IntegerField(default=0)
    skill_uml = models.IntegerField(default=0)
    skill_unix = models.IntegerField(default=0)
    skill_vb_net = models.IntegerField(default=0)
    skill_vba = models.IntegerField(default=0)
    skill_verbal_communication = models.IntegerField(default=0)
    skill_visio = models.IntegerField(default=0)
    skill_visual_basic = models.IntegerField(default=0)
    skill_vmware = models.IntegerField(default=0)
    skill_volleyball = models.IntegerField(default=0)
    skill_wcf = models.IntegerField(default=0)
    skill_web_analytics = models.IntegerField(default=0)
    skill_web_development = models.IntegerField(default=0)
    skill_web_services = models.IntegerField(default=0)
    skill_webgl = models.IntegerField(default=0)
    skill_website_development = models.IntegerField(default=0)
    skill_wi_fi = models.IntegerField(default=0)
    skill_wimax = models.IntegerField(default=0)
    skill_windows = models.IntegerField(default=0)
    skill_windows_a = models.IntegerField(default=0)
    skill_word = models.IntegerField(default=0)
    skill_wordpress = models.IntegerField(default=0)
    skill_wpf = models.IntegerField(default=0)
    skill_wsdl = models.IntegerField(default=0)
    skill_xaml = models.IntegerField(default=0)
    skill_xhtml = models.IntegerField(default=0)
    skill_xml = models.IntegerField(default=0)
    total_skills = models.IntegerField(default=0)
    

    def __str__(self):
        return (self.total_skills)

class Job_Listing(models.Model) :
    JobListing_ID = models.AutoField(primary_key=True) 
    JobTitle = models.CharField(max_length=100)
    JobCity = models.CharField(max_length=50)
    ContractType = models.CharField(max_length=50)
    JobDescription = models.CharField(max_length=10000)
    JobSkills_ID = models.ForeignKey('Skills', null=True, blank=True, on_delete=models.SET_NULL) 
    Listing_Status_ID = models.ForeignKey('Listing_Status', null=True, blank=True, on_delete=models.SET_NULL)
    Organization_ID = models.ForeignKey('Company', null=True, blank=True, on_delete=models.SET_NULL)

    def __str__(self):
        return (self.JobTitle)

class Job_Offer(models.Model) :
    JobOffer_ID = models.AutoField(primary_key=True)
    JobListing_ID = models.ForeignKey('Job_Listing', null=True, blank=True, on_delete=models.SET_NULL)
    Organization_ID = models.ForeignKey('Company', null=True, blank=True, on_delete=models.SET_NULL)
    Applicant_ID = models.ForeignKey('Applicant', null=True, blank=True, on_delete=models.SET_NULL)
    ApplicantSkills_ID = models.ForeignKey('Skills', null=True, blank=True, on_delete=models.SET_NULL)

    def __str__(self):
        return (self.JobOffer_ID)